AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for S3 and CloudFront hosting of a React application.

Resources:
  # S3 Bucket
  ReactAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: react-app-hosting-bucket-ahmed-ibrahim
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # S3 Bucket Policy
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ReactAppS3Bucket.Arn}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt ReactAppS3Bucket.WebsiteURL
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        PriceClass: PriceClass_100

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket hosting the React app
    Value: !Ref ReactAppS3Bucket
  CloudFrontURL:
    Description: URL of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
